services:
  chatbot:
    build:
      context: .
      dockerfile: Dockerfile
    image: arita-chatbot:latest
    container_name: arita-demo
    ports:
      - "8585:8585"
    volumes:
      - ./database:/app/temp_user_files
    env_file:
      - .env
    restart: unless-stopped
    extra_hosts:
      - host.docker.internal:host-gateway
    dns:
      - 10.202.10.202
      - 10.202.10.102
    networks:
      - demo_shared-network

networks:
  demo_shared-network:
    external: true