services:
  chromadb:
    build:
      context: .
      dockerfile: Dockerfile
    image: chromadb/chroma:latest
    container_name: chroma-server
    ports:
      - "8324:8324"
    volumes:
      - ./database:/app/chroma
      - .:/app
    env_file:
      - .env
    restart: unless-stopped
    extra_hosts:
      - host.docker.internal:host-gateway
    # dns:
    #   - 10.202.10.202
    #   - 10.202.10.102
    networks:
      - shared-network

networks:
  shared-network:
    driver: bridge